import 'package:flutter/material.dart';import 'package:reels_share_app/core/app_export.dart';import 'package:reels_share_app/presentation/posts_add_sounds_page/posts_add_sounds_page.dart';import 'package:reels_share_app/widgets/app_bar/appbar_image.dart';import 'package:reels_share_app/widgets/app_bar/appbar_title.dart';import 'package:reels_share_app/widgets/app_bar/custom_app_bar.dart';import 'package:reels_share_app/widgets/custom_search_view.dart';class PostsAddSoundsTabContainerScreen extends StatefulWidget {@override _PostsAddSoundsTabContainerScreenState createState() =>  _PostsAddSoundsTabContainerScreenState();
onTapClose(BuildContext context) { Navigator.pop(context); } 
 }

// ignore_for_file: must_be_immutable

// ignore_for_file: must_be_immutable
class _PostsAddSoundsTabContainerScreenState extends State<PostsAddSoundsTabContainerScreen> with  TickerProviderStateMixin {TextEditingController stateDefaultSearchController = TextEditingController();

late TabController autolayouthorizontalController;

@override void initState() { super.initState(); autolayouthorizontalController = TabController(length: 2, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, resizeToAvoidBottomInset: false, appBar: CustomAppBar(height: getVerticalSize(44), leadingWidth: 52, leading: AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgClose28x28, margin: getMargin(left: 24, top: 8, bottom: 7), onTap: () {onTapClose(context);}), centerTitle: true, title: AppbarTitle(text: "All Sounds"), actions: [AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgClock24x24, margin: getMargin(left: 24, top: 8, right: 24, bottom: 7))]), body: Container(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Align(alignment: Alignment.center, child: CustomSearchView(focusNode: FocusNode(), controller: stateDefaultSearchController, hintText: "Search", margin: getMargin(left: 24, top: 24, right: 24), alignment: Alignment.center, prefix: Container(margin: getMargin(left: 20, top: 18, right: 12, bottom: 18), child: CustomImageView(svgPath: ImageConstant.imgSearchGray400)), prefixConstraints: BoxConstraints(maxHeight: getVerticalSize(56)), suffix: Container(margin: getMargin(left: 30, top: 18, right: 20, bottom: 18), child: CustomImageView(svgPath: ImageConstant.imgOverflowmenu)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(56)))), Container(height: getVerticalSize(39), width: getHorizontalSize(322), margin: getMargin(left: 24, top: 25), child: TabBar(controller: autolayouthorizontalController, labelColor: ColorConstant.deepOrangeA40001, labelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), unselectedLabelColor: ColorConstant.gray500, unselectedLabelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), indicatorColor: ColorConstant.deepOrangeA40001, tabs: [Tab(child: Text("Discover", overflow: TextOverflow.ellipsis)), Tab(child: Text("Favorites", overflow: TextOverflow.ellipsis))])), Container(height: getVerticalSize(691), child: TabBarView(controller: autolayouthorizontalController, children: [PostsAddSoundsPage(), PostsAddSoundsPage()]))])))); } 
onTapClose(BuildContext context) { Navigator.pop(context); } 
 }
