import 'package:flutter/material.dart';import 'package:reels_share_app/core/app_export.dart';import 'package:reels_share_app/widgets/app_bar/appbar_image.dart';import 'package:reels_share_app/widgets/app_bar/appbar_title.dart';import 'package:reels_share_app/widgets/app_bar/custom_app_bar.dart';import 'package:reels_share_app/widgets/custom_button.dart';import 'package:reels_share_app/widgets/custom_text_form_field.dart';import 'package:reels_share_app/presentation/reset_password_successful_dialog/reset_password_successful_dialog.dart';
// ignore_for_file: must_be_immutable

// ignore_for_file: must_be_immutable
class CreateNewPasswordScreen extends StatelessWidget {TextEditingController statusFillTypePasswordController = TextEditingController();

TextEditingController statusFillTypePasswordOneController = TextEditingController();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, resizeToAvoidBottomInset: false, appBar: CustomAppBar(height: getVerticalSize(48), leadingWidth: 52, leading: AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 24, top: 10, bottom: 10), onTap: () {onTapArrowleft9(context);}), title: AppbarTitle(text: "Create New Password", margin: getMargin(left: 16))), body: Container(width: double.maxFinite, padding: getPadding(left: 24, top: 117, right: 24), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.start, children: [Text("Create Your New Password", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRomanMedium18.copyWith(letterSpacing: getHorizontalSize(0.2))), CustomTextFormField(focusNode: FocusNode(), controller: statusFillTypePasswordController, hintText: "Enter New Password", margin: getMargin(top: 25), textInputType: TextInputType.visiblePassword, prefix: Container(margin: getMargin(left: 20, top: 18, right: 12, bottom: 22), child: CustomImageView(svgPath: ImageConstant.imgLock)), prefixConstraints: BoxConstraints(maxHeight: getVerticalSize(60)), suffix: Container(margin: getMargin(left: 12, top: 18, right: 20, bottom: 22), child: CustomImageView(svgPath: ImageConstant.imgDashboard20x20)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(60))), CustomTextFormField(focusNode: FocusNode(), controller: statusFillTypePasswordOneController, hintText: "Confirm New Password", margin: getMargin(top: 24), textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, prefix: Container(margin: getMargin(left: 20, top: 18, right: 12, bottom: 22), child: CustomImageView(svgPath: ImageConstant.imgLock)), prefixConstraints: BoxConstraints(maxHeight: getVerticalSize(60)), suffix: Container(margin: getMargin(left: 30, top: 18, right: 20, bottom: 22), child: CustomImageView(svgPath: ImageConstant.imgDashboard20x20)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(60))), CustomButton(height: getVerticalSize(58), text: "Continue", margin: getMargin(top: 24, bottom: 5), variant: ButtonVariant.OutlineDeeporangeA40035, shape: ButtonShape.RoundedBorder16, padding: ButtonPadding.PaddingAll18, fontStyle: ButtonFontStyle.UrbanistRomanBold16WhiteA700, onTap: () {onTapContinue(context);})])))); } 
onTapContinue(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: ResetPasswordSuccessfulDialog(),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: EdgeInsets.only(left: 0),)); } 
onTapArrowleft9(BuildContext context) { Navigator.pop(context); } 
 }
